
import java.awt.*;
import java.io.*;
import java.util.logging.*;
import javax.imageio.ImageIO;
import javax.swing.*;
import javax.swing.table.*;
import java.sql.*;
import java.util.ArrayList;
import db.DBLoader;

    
public class AdminManageCars extends javax.swing.JFrame {

    ResultSet rs;
    ArrayList<car_details> alr = new ArrayList<>();
    mytablemodel mt;
    /**
     * Creates new form AdminManageCars
     */
    public AdminManageCars() throws IOException {
        
        rs = DBLoader.executeQuery("select * from car_details");
        try{
            while(rs.next()){
                int cid = rs.getInt("car_id");
                String cnm = rs.getString("car_name");
                String brd = rs.getString("brand");
                String cty = rs.getString("car_type");
                String fty = rs.getString("fuel_type");
                int pwod = rs.getInt("price_per_day_without_driver");
                int pwid = rs.getInt("price_per_day_with_driver");
                int secu = rs.getInt("security");
                String desp = rs.getString("description");
                String nplt = rs.getString("numberplate");
                String pht = rs.getString("photo");
                
                alr.add(new car_details(cid, cnm, brd, cty, fty, pwod, pwid, secu, desp,nplt, pht));
            }
        }
        catch(Exception ex){
            ex.printStackTrace();
        }
        
        mt = new mytablemodel();
        
        ImageIcon im;
        try {
            im = new ImageIcon(ImageIO.read(new File("src\\myuploads\\generated-image (1).png")));
            setContentPane(new JLabel(im));
        } catch (IOException ex) {
            Logger.getLogger(Welcome.class.getName()).log(Level.SEVERE, null, ex);
        }
        repaint();
        
        initComponents();

//        // JFrame opens at screen size at fullscreen1
//        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
//        setSize(screenSize.width, screenSize.height);

        // JFrame opens at screen size at fullscreen2
        setExtendedState(MAXIMIZED_BOTH);
        
//        // JFrame opens at screen size at fullscreen3
//        setSize(getMaximumSize());
        
        jPanel1.setOpaque(false);
        jPanel2.setOpaque(false);
        setResizable(false);
        setLocationRelativeTo(null);
        setTitle("Admin Manage Cars");
        jPanel1.requestFocus();
        backbutton.setText("\uD83E\uDC60");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new blurpanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        backbutton = new mybuttondesign();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new mybuttondesign();
        jButton3 = new mybuttondesign();
        jButton2 = new mybuttondesign();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Rockwell", 0, 80)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Already Added Cars");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(260, 20, 780, 100);

        jTable1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTable1.setModel(mt);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(60, 130, 1190, 510);

        backbutton.setText("Back");
        backbutton.setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 12, 6, 12));
        backbutton.setBorderPainted(false);
        backbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(backbutton);
        backbutton.setBounds(10, 10, 50, 30);

        jPanel2.setLayout(null);

        jButton1.setFont(new java.awt.Font("Rockwell", 0, 24)); // NOI18N
        jButton1.setText("Add New Car");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(0, 0, 350, 70);

        jButton3.setFont(new java.awt.Font("Rockwell", 0, 24)); // NOI18N
        jButton3.setText("Edit Car");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(420, 0, 350, 70);

        jButton2.setFont(new java.awt.Font("Rockwell", 0, 24)); // NOI18N
        jButton2.setText("Remove Car");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(840, 0, 350, 70);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 660, 1190, 70);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(50, 20, 1430, 770);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new AdminAddCar().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(jTable1.getSelectedRow() == -1){
            JOptionPane.showMessageDialog(this, "Please select a row first.");
        }
        else{
            int c = JOptionPane.showConfirmDialog(this, "Do you really want to remove this row ?", "Confrim Delete", JOptionPane.YES_NO_OPTION );
                if(c == JOptionPane.YES_OPTION){
                int idx = jTable1.getSelectedRow();
                int cdc = alr.get(idx).cid;
                alr.remove(idx);
                ResultSet rs = DBLoader.executeQuery("select * from car_details where car_id = "+cdc);
                try {
                    if(rs.next()){
                       rs.deleteRow();
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(AdminManageCars.class.getName()).log(Level.SEVERE, null, ex);
                }
                mt.fireTableDataChanged();
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void backbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttonActionPerformed
        try {
            new AdminHome().setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(AdminChangePassword.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }//GEN-LAST:event_backbuttonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        if(jTable1.getSelectedRow() == -1){
            JOptionPane.showMessageDialog(this, "Please select a row to edit first.");
        }
        else{
            int c = JOptionPane.showConfirmDialog(this, "Do you really want to edit a row ?", "Confrim Edit", JOptionPane.YES_NO_OPTION );
            if(c == JOptionPane.YES_OPTION){
                    int idx = jTable1.getSelectedRow();
                    int cdc = alr.get(idx).cid;
                    try {
                        AdminEditCars ed = new AdminEditCars(cdc);
                        ed.setVisible(true);
                        dispose();
                    } catch (Exception ex) {
                        Logger.getLogger(AdminManageCars.class.getName()).log(Level.SEVERE, null, ex);
                    }
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        jPanel1.setBounds(10,10,getWidth()-35,getHeight()-55);
        jScrollPane1.setBounds((jPanel1.getWidth()-1350)/2,(jPanel1.getHeight()-510)/2,1350,510);
        jLabel1.setBounds((jPanel1.getWidth()-780)/2,(jScrollPane1.getY()-100)/2,780,100);
        jPanel2.setBounds((jPanel1.getWidth()-1190)/2,jScrollPane1.getY()+jScrollPane1.getHeight()+(jPanel1.getHeight()-jScrollPane1.getY()-jScrollPane1.getHeight()-70)/2,1190,70);
        backbutton.setBounds(5,5,30,30);
    }//GEN-LAST:event_formComponentResized

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminManageCars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminManageCars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminManageCars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminManageCars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new AdminManageCars().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(AdminManageCars.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    
    class mytablemodel extends AbstractTableModel{

        @Override
        public int getRowCount() {
            return alr.size();
        }

        @Override
        public int getColumnCount() {
            return 11;
        }

        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
            car_details cd = alr.get(rowIndex);
            
            return switch (columnIndex) {
                case 0 -> cd.cid;
                case 1 -> cd.cnm;
                case 2 -> cd.brd;
                case 3 -> cd.cty;
                case 4 -> cd.fty;
                case 5 -> cd.pwod;
                case 6 -> cd.pwid;
                case 7 -> cd.secu;
                case 8 -> cd.desp;
                case 9 -> cd.nplt;
                case 10 -> cd.pht;
                default -> null;
            };
        }

        @Override
        public String getColumnName(int column) {
            String head[] = {"Car_id","Car_Name","Brand","Car_Type","Fuel_Type","Price_per_day_without_driver","Price_per_day_with_driver","Security","Description","Numberplate","Photo"};
            
            return head[column];
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbutton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
