
import java.io.*;
import java.util.*;
import java.sql.*;
import java.util.logging.*;
import javax.imageio.ImageIO;
import javax.swing.*;
import javax.swing.table.AbstractTableModel;
import db.DBLoader;


public class AdminBookingHistory extends javax.swing.JFrame {

    ResultSet rs; 
    ArrayList<booking> alr = new ArrayList<>();
    mytablemodel mt;
    /**
     * Creates new form AdminBookingHistory
     */
    public AdminBookingHistory() {
        rs = DBLoader.executeQuery("select * from booking");
        try {
            while(rs.next()){
                int booking_id = rs.getInt("booking_id");
                int car_id = rs.getInt("car_id");
                int price_per_day = rs.getInt("price_per_day");
                String start_date = rs.getString("start_date");
                String end_date = rs.getString("end_date");
                int no_of_days = rs.getInt("no_of_days");
                int total_rent = rs.getInt("total_rent");
                String name = rs.getString("name");
                String mobile_no = rs.getString("mobile_no");
                String address = rs.getString("address");
                String email = rs.getString("email");
                String payment_status = rs.getString("payment_status");
                String booking_status = rs.getString("booking_status");
                
                alr.add(new booking(booking_id, car_id, price_per_day, start_date, end_date, no_of_days, total_rent, name, mobile_no, address, email, payment_status, booking_status));
            }
        } catch (SQLException ex) {
            Logger.getLogger(AdminBookingHistory.class.getName()).log(Level.SEVERE, null, ex);
        }
        mt = new mytablemodel();
        ImageIcon im;
        try {
            im = new ImageIcon(ImageIO.read(new File("src\\myuploads\\generated-image (1).png")));
            setContentPane(new JLabel(im));
        } catch (IOException ex) {
            Logger.getLogger(Welcome.class.getName()).log(Level.SEVERE, null, ex);
        }
        repaint();
        initComponents();
        jPanel1.setOpaque(false);
        setSize(841,451);
        setExtendedState(MAXIMIZED_BOTH);
        setTitle("Admin Booking History");
        setLocationRelativeTo(null);
        jPanel1.requestFocus();
        backbutton.setText("\uD83E\uDC60");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new blurpanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        backbutton = new mybuttondesign();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Rockwell", 0, 80)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Booking History");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(250, 0, 600, 100);

        jTable1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTable1.setModel(mt);
        jTable1.getTableHeader().setResizingAllowed(false);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(30, 110, 1130, 650);

        backbutton.setText("Back");
        backbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(backbutton);
        backbutton.setBounds(10, 10, 100, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(50, 60, 1190, 810);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttonActionPerformed
        try {
            new AdminHome().setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(AdminBookingHistory.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }//GEN-LAST:event_backbuttonActionPerformed

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        jPanel1.setBounds(10,10,getWidth()-35,getHeight()-55);
        jScrollPane1.setBounds((jPanel1.getWidth()-1450)/2,jPanel1.getHeight()-600-30,1450,600);
        jLabel1.setBounds((jPanel1.getWidth()-780)/2,(jScrollPane1.getY()-100)/2,780,100);
        backbutton.setBounds(5,5,30,30);
    }//GEN-LAST:event_formComponentResized

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminBookingHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminBookingHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminBookingHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminBookingHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminBookingHistory().setVisible(true);
            }
        });
    }
    
    class mytablemodel extends AbstractTableModel{

        @Override
        public int getRowCount() {
            return alr.size();
        }

        @Override
        public int getColumnCount() {
            return 13;
        }

        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
            booking bk = alr.get(rowIndex);
            
            switch (columnIndex) {
                case 0:
                    return bk.booking_id;
                case 1:
                    return bk.car_id;
                case 2:
                    return bk.price_per_day;
                case 3:
                    return bk.start_date;
                case 4:
                    return bk.end_date;
                case 5:
                    return bk.no_of_days;
                case 6:
                    return bk.total_rent;
                case 7:
                    return bk.name;
                case 8:
                    return bk.mobile_no;
                case 9:
                    return bk.address;
                case 10:
                    return bk.email;
                case 11:
                    return bk.payment_status;
                case 12:
                    return bk.booking_status;
                default:
                    throw new AssertionError();
            }
        }

        @Override
        public String getColumnName(int column) {
            String head[] = {"Booking id","Car id","Price per Day","Start Date","End Date","No of Days","Rent","Name","Mobile No","Address","Email","Payment Status","Booking Status"};
            return head[column];
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
