
import java.awt.*;
import static java.awt.event.KeyEvent.*;
import java.io.File;
import java.io.IOException;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;
import db.DBLoader;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author DELL
 */
public class AdminEditCars extends javax.swing.JFrame {

    private static String path="";
    private static int id;
    /**
     * Creates new form AdminEditCars
     */
    public AdminEditCars(int a) {
        ImageIcon im;
        try {
            im = new ImageIcon(ImageIO.read(new File("src\\myuploads\\generated-image (1).png")));
            setContentPane(new JLabel(im));
        } catch (IOException ex) {
            Logger.getLogger(Welcome.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
        jPanel1.setOpaque(false);
        setSize(1205,775);
        setResizable(false);
        setTitle("Admin Edit Car");
        setLocationRelativeTo(null);
        getRootPane().setDefaultButton(jButton2);
        jTextField1.requestFocus();
        this.id = a;
        getdata();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new blurpanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new mybuttondesign();
        jButton2 = new mybuttondesign();
        jTextField5 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        backbutton = new mybuttondesign();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Rockwell", 0, 80)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Edit Car");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(425, 20, 320, 90);

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel12);
        jLabel12.setBounds(750, 340, 200, 180);

        jTextField1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(240, 140, 230, 30);

        jComboBox1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Brand", "Ford", "Volkswagon", "Maruti Suzuki", "Hyundai", "Tata Motors", "Mahindra & Mahindra", "Kia", "Honda", "Toyota", "Renault", "MG Motor", "Skoda", "BMW", "Audi", "Nissan", "Land Rover", "Mercedes-Benz" }));
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(240, 190, 230, 30);

        jComboBox2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Type", "Van", "Mini-Van", "Truck", "Mini-truck", "Passenger" }));
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(240, 240, 230, 30);

        jComboBox3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Fuel Type", "Petrol", "Diesel", "Electricity", "CNG", "LPG", "Hybrid", " " }));
        jPanel1.add(jComboBox3);
        jComboBox3.setBounds(240, 290, 230, 30);

        jTextField2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField2KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField2);
        jTextField2.setBounds(240, 390, 230, 30);

        jTextField3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField3KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField3);
        jTextField3.setBounds(240, 440, 230, 30);

        jTextField4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField4KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField4);
        jTextField4.setBounds(240, 490, 230, 30);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextArea1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(750, 140, 390, 130);

        jButton1.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        jButton1.setText("Choose Photo");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(970, 390, 140, 27);

        jButton2.setFont(new java.awt.Font("Rockwell", 0, 28)); // NOI18N
        jButton2.setText("Edit");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(420, 570, 320, 80);

        jTextField5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField5KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField5);
        jTextField5.setBounds(750, 290, 230, 30);

        jLabel2.setFont(new java.awt.Font("Rockwell", 0, 22)); // NOI18N
        jLabel2.setText("Car Name :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 140, 200, 30);

        jLabel3.setFont(new java.awt.Font("Rockwell", 0, 22)); // NOI18N
        jLabel3.setText("Brand :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 190, 200, 30);

        jLabel4.setFont(new java.awt.Font("Rockwell", 0, 22)); // NOI18N
        jLabel4.setText("Car Type :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 240, 200, 30);

        jLabel5.setFont(new java.awt.Font("Rockwell", 0, 22)); // NOI18N
        jLabel5.setText("Fuel Type :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 290, 200, 30);

        jLabel6.setFont(new java.awt.Font("Rockwell", 0, 22)); // NOI18N
        jLabel6.setText("Price Per Day :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 340, 200, 30);

        jLabel7.setFont(new java.awt.Font("Rockwell", 0, 22)); // NOI18N
        jLabel7.setText("With Driver :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(30, 390, 200, 30);

        jLabel8.setFont(new java.awt.Font("Rockwell", 0, 22)); // NOI18N
        jLabel8.setText("Without Driver :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(30, 440, 200, 30);

        jLabel10.setFont(new java.awt.Font("Rockwell", 0, 22)); // NOI18N
        jLabel10.setText("Description :");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(540, 140, 200, 30);

        jLabel13.setFont(new java.awt.Font("Rockwell", 0, 22)); // NOI18N
        jLabel13.setText("Numberplate : ");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(540, 290, 200, 30);

        jLabel11.setFont(new java.awt.Font("Rockwell", 0, 22)); // NOI18N
        jLabel11.setText("Photo :");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(540, 340, 160, 30);

        jLabel9.setFont(new java.awt.Font("Rockwell", 0, 22)); // NOI18N
        jLabel9.setText("Security :");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(30, 490, 200, 30);

        backbutton.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        backbutton.setText("Cancel");
        backbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(backbutton);
        backbutton.setBounds(520, 670, 120, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(70, 50, 1170, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser JF1 = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
        "JPG , JPEG , GIF & PNG Images", "jpg", "gif" , "png", "jpeg");
        JF1.setFileFilter(filter);
        int returnVal = JF1.showOpenDialog(this);
        if(returnVal == JFileChooser.APPROVE_OPTION) {
            File f1 = JF1.getSelectedFile();
            String path = f1.getPath();
            int pa = path.indexOf("src");
            this.path = path.substring(pa);

            // Get Resized Image
            jLabel12.setIcon(new ImageIcon(new ImageIcon(this.path).getImage().getScaledInstance(130, 120, Image.SCALE_DEFAULT)));
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        String cnm = jTextField1.getText();
        String brd = jComboBox1.getSelectedItem().toString();
        String cty = jComboBox2.getSelectedItem().toString();
        String fty = jComboBox3.getSelectedItem().toString();
        int pwid = Integer.parseInt(jTextField2.getText().isEmpty() ? "0" : jTextField2.getText());
        int pwod = Integer.parseInt(jTextField3.getText().isEmpty() ? "0" : jTextField3.getText());
        int secu = Integer.parseInt(jTextField4.getText().isEmpty() ? "0" : jTextField3.getText());
        String desp = jTextArea1.getText();
        String nplt = jTextField5.getText();
        String pht = this.path;
        if(cnm.isEmpty() || brd.equals("Select Brand") || cty.equals("Select Type") || fty.equals("Select Fuel Type") || pwid==0 || pwod==0 || secu==0 || nplt.isEmpty() || desp.isEmpty() || pht.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please fill all the fields");
        }
        else{
            ResultSet rs = DBLoader.executeQuery("select * from car_details where car_id = '"+this.id+"'");
            try {
                if(rs.next()){
                    rs.updateString("car_name", cnm);
                    rs.updateString("brand", brd);
                    rs.updateString("car_type", cty);
                    rs.updateString("fuel_type", fty);
                    rs.updateInt("price_per_day_with_driver", pwid);
                    rs.updateInt("price_per_day_without_driver", pwod);
                    rs.updateInt("security", secu);
                    rs.updateString("description", desp);
                    rs.updateString("numberplate", nplt);
                    rs.updateString("photo", pht);

                    rs.updateRow();
                    JOptionPane.showMessageDialog(this, "Car Edited Successfully");
                    try {
                        new AdminManageCars().setVisible(true);
                    } catch (IOException ex) {
                        Logger.getLogger(AdminChangePassword.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    dispose();
                }
                else{
                    JOptionPane.showMessageDialog(this, "Car does not exist");
                }
            } catch (SQLException ex) {
                Logger.getLogger(AdminAddCar.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void backbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttonActionPerformed
        try {
            new AdminManageCars().setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(AdminChangePassword.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }//GEN-LAST:event_backbuttonActionPerformed

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        jPanel1.setBounds(10,10, 1170, 720);
    }//GEN-LAST:event_formComponentResized

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        if(evt.getKeyCode() == VK_DOWN){
            jTextField2.requestFocus();
        }
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jTextField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyPressed
        if(evt.getKeyCode() == VK_DOWN){
            jTextField3.requestFocus();
        }
        else if(evt.getKeyCode() == VK_UP){
            jTextField1.requestFocus();
        }
    }//GEN-LAST:event_jTextField2KeyPressed

    private void jTextField3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyPressed
        if(evt.getKeyCode() == VK_DOWN){
            jTextField4.requestFocus();
        }
        else if(evt.getKeyCode() == VK_UP){
            jTextField2.requestFocus();
        }
    }//GEN-LAST:event_jTextField3KeyPressed

    private void jTextField4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyPressed
        if(evt.getKeyCode() == VK_DOWN){
            jTextArea1.requestFocus();
        }
        else if(evt.getKeyCode() == VK_UP){
            jTextField3.requestFocus();
        }
    }//GEN-LAST:event_jTextField4KeyPressed

    private void jTextArea1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextArea1KeyPressed
        if(evt.getKeyCode() == VK_UP){
            jTextField4.requestFocus();
        }
        else if(evt.getKeyCode() == VK_DOWN){
            jTextField5.requestFocus();
        }
    }//GEN-LAST:event_jTextArea1KeyPressed

    private void jTextField5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyPressed
        if(evt.getKeyCode() == VK_UP){
            jTextArea1.requestFocus();
        }
    }//GEN-LAST:event_jTextField5KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminEditCars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminEditCars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminEditCars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminEditCars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminEditCars(0).setVisible(true);
            }
        });
    }
    
    private void getdata(){
        ResultSet rs = DBLoader.executeQuery("select * from car_details where car_id = '"+this.id+"'");
        try {
            if(rs.next()){
                jTextField1.setText(rs.getString("car_name"));
                jComboBox1.setSelectedIndex(cboxselct(jComboBox1, rs.getString("brand")));
                jComboBox2.setSelectedIndex(cboxselct(jComboBox2, rs.getString("car_type")));
                jComboBox3.setSelectedIndex(cboxselct(jComboBox3, rs.getString("fuel_type")));
                jTextField2.setText(rs.getInt("Price_per_day_without_driver")+"");
                jTextField3.setText(rs.getInt("Price_per_day_with_driver")+"");
                jTextField4.setText(rs.getString("security")+"");
                jTextArea1.setText(rs.getString("description"));
                this.path = rs.getString("photo");
                jLabel12.setIcon(new ImageIcon(new ImageIcon(this.path).getImage().getScaledInstance(130, 120, Image.SCALE_DEFAULT)));
            }
        } catch (SQLException ex) {
            Logger.getLogger(AdminEditCars.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
//    
    int cboxselct(JComboBox c,String s){
        int a1 = c.getItemCount();
        int i = 0;
        int a = -1;
        while(i<a1){
            String s2 = c.getItemAt(i).toString();
            if(s.equals(s2)){
                a = i;
            }
            i++;
        }
        return a;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbutton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
