 import java.awt.*;
import java.io.*;
import java.sql.*;
import java.util.logging.*;
import javax.imageio.ImageIO;
import javax.swing.*;
import db.DBLoader;

public class BookingSelect extends javax.swing.JFrame {

    private int cid;
    private int price;
    
    
    public BookingSelect(int a) {
        ImageIcon im;
        try {
            im = new ImageIcon(ImageIO.read(new File("src\\myuploads\\generated-image (1).png")));
            setContentPane(new JLabel(im));
        } catch (IOException ex) {
            Logger.getLogger(Welcome.class.getName()).log(Level.SEVERE, null, ex);
        }
        repaint();
        initComponents();
        setSize(695,795);
        setTitle("Bookings");
        setLocationRelativeTo(null);
        jPanel1.setOpaque(false);
        getRootPane().setDefaultButton(jButton1);
        
        buttonGroup1.add(jRadioButton1);
        buttonGroup1.add(jRadioButton2);
        
        this.cid = a;
        getcar(a);
    }
    
    private void getcar(int i){
        ResultSet rs = DBLoader.executeQuery("select * from car_details where car_id =" + i);
        try {
            rs.next();
            jLabel2.setIcon(new ImageIcon( new ImageIcon(rs.getString("photo")).getImage().getScaledInstance(jLabel2.getWidth(), -1, Image.SCALE_SMOOTH)));
            jLabel3.setText("Car Name : "+rs.getString("Car_name"));
            jLabel4.setText("Brand : "+rs.getString("brand"));
            jLabel5.setText("Car Type : "+rs.getString("car_type"));
            jLabel11.setText("Fuel Type : "+rs.getString("fuel_type"));
            jLabel12.setText("Security : "+rs.getInt("security"));
            jRadioButton1.setText(rs.getString("Price_per_day_with_driver"));
            jRadioButton2.setText(rs.getString("Price_per_day_without_driver"));
        } catch (SQLException ex) {
            Logger.getLogger(BookingSelect.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new blurpanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jButton1 = new mybuttondesign();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        backbutton = new mybuttondesign();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Rockwell", 0, 55)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Booking");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(170, 10, 350, 70);
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 100, 320, 250);

        jLabel3.setFont(new java.awt.Font("Rockwell", 0, 22)); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(380, 100, 250, 30);

        jLabel4.setFont(new java.awt.Font("Rockwell", 0, 22)); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(380, 150, 250, 30);

        jLabel5.setFont(new java.awt.Font("Rockwell", 0, 22)); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(380, 200, 250, 30);

        jLabel7.setFont(new java.awt.Font("Rockwell", 0, 22)); // NOI18N
        jLabel7.setText("Without Driver ");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(170, 430, 160, 30);

        jLabel8.setFont(new java.awt.Font("Rockwell", 0, 22)); // NOI18N
        jLabel8.setText("With Driver ");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(170, 470, 160, 30);

        jLabel9.setFont(new java.awt.Font("Rockwell", 0, 22)); // NOI18N
        jLabel9.setText("From Date :");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(170, 530, 140, 30);

        jLabel10.setFont(new java.awt.Font("Rockwell", 0, 22)); // NOI18N
        jLabel10.setText("To Date :");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(170, 570, 140, 30);

        jRadioButton1.setFont(new java.awt.Font("Rockwell", 0, 22)); // NOI18N
        jRadioButton1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton1ItemStateChanged(evt);
            }
        });
        jPanel1.add(jRadioButton1);
        jRadioButton1.setBounds(340, 430, 160, 30);

        jRadioButton2.setFont(new java.awt.Font("Rockwell", 0, 22)); // NOI18N
        jRadioButton2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton2ItemStateChanged(evt);
            }
        });
        jPanel1.add(jRadioButton2);
        jRadioButton2.setBounds(340, 470, 160, 30);

        jButton1.setFont(new java.awt.Font("Rockwell", 0, 24)); // NOI18N
        jButton1.setText("Book");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(210, 630, 240, 60);

        jDateChooser1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jDateChooser1);
        jDateChooser1.setBounds(330, 530, 180, 30);

        jDateChooser2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jDateChooser2);
        jDateChooser2.setBounds(330, 570, 180, 30);

        jLabel6.setFont(new java.awt.Font("Rockwell", 0, 22)); // NOI18N
        jLabel6.setText("Select Price :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(170, 370, 200, 40);

        jLabel11.setFont(new java.awt.Font("Rockwell", 0, 22)); // NOI18N
        jLabel11.setText("jLabel11");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(380, 250, 250, 30);

        jLabel12.setFont(new java.awt.Font("Rockwell", 0, 22)); // NOI18N
        jLabel12.setText("jLabel12");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(380, 300, 250, 30);

        backbutton.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        backbutton.setText("Cancel");
        backbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(backbutton);
        backbutton.setBounds(267, 700, 120, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(290, 60, 660, 740);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(this.price == 0 || jDateChooser1.getDate() == null || jDateChooser2.getDate() == null){
            JOptionPane.showMessageDialog(this, "Please Select all the fields Appropriately");
        }
        else{
            String d1 = jDateChooser1.getDate().toString();
            String d2 = jDateChooser2.getDate().toString();
            int da1 = Integer.parseInt(d1.substring(8,10));
            int da2 = Integer.parseInt(d2.substring(8,10));
            if(da2 >= da1){
                int dy1 = day(d1.substring(4,7));
                int dy2 = day(d2.substring(4,7));
                d1 = da1+"-"+dy1+"-"+d1.substring(24);
                d2 = da2+"-"+dy2+"-"+d2.substring(24);
                int nod = da2-da1+1;
                int rent = this.price*nod;
                int security = Integer.parseInt(jLabel12.getText().substring(11));
                new BookingFinal(this.cid,this.price,d1,d2,nod,rent,security).setVisible(true);
                dispose();
            }
            else{
                JOptionPane.showMessageDialog(this, "The End Date Should not be Lesser than the Start Date");
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton1ItemStateChanged
        this.price = Integer.parseInt(jRadioButton1.getText());
    }//GEN-LAST:event_jRadioButton1ItemStateChanged

    private void jRadioButton2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton2ItemStateChanged
        this.price = Integer.parseInt(jRadioButton2.getText());
    }//GEN-LAST:event_jRadioButton2ItemStateChanged

    private void backbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttonActionPerformed
        dispose();
    }//GEN-LAST:event_backbuttonActionPerformed

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        jPanel1.setBounds(10,10, jPanel1.getWidth(), jPanel1.getHeight());
    }//GEN-LAST:event_formComponentResized
 
    private int day(String var){
        switch (var) {
            case "Jan":
                return 1;
            case "Feb":
                return 2;
            case "Mar":
                return 3;
            case "Apr":
                return 4;
            case "May":
                return 5;
            case "Jun":
                return 6;
            case "Jul":
                return 7;
            case "Aug":
                return 8;
            case "Sep":
                return 9;
            case "Oct":
                return 10;
            case "Nov":
                return 11;
            case "Dec":
                return 12;
            default:
                throw new AssertionError();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookingSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookingSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookingSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookingSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookingSelect(0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbutton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    // End of variables declaration//GEN-END:variables
}
