import static java.awt.event.KeyEvent.*;
import java.io.*;
import java.sql.*;
import java.util.logging.*;
import javax.imageio.ImageIO;
import javax.swing.*;
import javax.swing.JOptionPane;
import db.DBLoader;

public class BookingFinal extends javax.swing.JFrame {

    /**
     * Creates new form BookingFinal
     */
    private int id;
    public BookingFinal(int id,int price,String start,String end,int num,int rent,int sec) {
        ImageIcon im;
        try {
            im = new ImageIcon(ImageIO.read(new File("src\\myuploads\\generated-image (1).png")));
            setContentPane(new JLabel(im));
        } catch (IOException ex) {
            Logger.getLogger(Welcome.class.getName()).log(Level.SEVERE, null, ex);
        }
        repaint();
        initComponents();
        jPanel1.setOpaque(false);
        setSize(1035, 545);
        setTitle("Booking Submission");
        setLocationRelativeTo(null);
        getRootPane().setDefaultButton(jButton1);
        jTextField1.requestFocus();
        this.id = id;
        getvalues(id,price,start,end,num,rent,sec);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new blurpanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new mybuttondesign();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        backbutton = new mybuttondesign();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Rockwell", 0, 55)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Booking Submission");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(215, 20, 570, 70);

        jLabel2.setFont(new java.awt.Font("Rockwell", 0, 22)); // NOI18N
        jLabel2.setText("Car ID : ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 110, 200, 30);

        jLabel3.setFont(new java.awt.Font("Rockwell", 0, 22)); // NOI18N
        jLabel3.setText("Price Per Day : ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 150, 200, 30);

        jLabel4.setFont(new java.awt.Font("Rockwell", 0, 22)); // NOI18N
        jLabel4.setText("Start Date : ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 190, 200, 30);

        jLabel5.setFont(new java.awt.Font("Rockwell", 0, 22)); // NOI18N
        jLabel5.setText("End Date : ");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 230, 200, 30);

        jLabel6.setFont(new java.awt.Font("Rockwell", 0, 22)); // NOI18N
        jLabel6.setText("No. of Days : ");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 270, 200, 30);

        jLabel7.setFont(new java.awt.Font("Rockwell", 0, 22)); // NOI18N
        jLabel7.setText("Rent : ");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(30, 310, 200, 30);

        jLabel8.setFont(new java.awt.Font("Rockwell", 0, 22)); // NOI18N
        jLabel8.setText("Security : ");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(520, 110, 200, 30);

        jLabel9.setFont(new java.awt.Font("Rockwell", 0, 22)); // NOI18N
        jLabel9.setText("Name : ");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(520, 190, 200, 30);

        jLabel10.setFont(new java.awt.Font("Rockwell", 0, 22)); // NOI18N
        jLabel10.setText("Phone Number : ");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(520, 230, 200, 30);

        jLabel11.setFont(new java.awt.Font("Rockwell", 0, 22)); // NOI18N
        jLabel11.setText("Address : ");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(520, 270, 200, 30);

        jLabel13.setFont(new java.awt.Font("Rockwell", 0, 22)); // NOI18N
        jLabel13.setText("Payment : ");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(520, 310, 200, 30);

        jTextField1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(720, 190, 250, 30);

        jTextField2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField2KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField2);
        jTextField2.setBounds(720, 230, 250, 30);

        jTextField3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField3KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField3);
        jTextField3.setBounds(720, 270, 250, 30);

        jButton1.setFont(new java.awt.Font("Rockwell", 0, 24)); // NOI18N
        jButton1.setText("Submit");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(365, 370, 240, 60);

        jLabel14.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jPanel1.add(jLabel14);
        jLabel14.setBounds(230, 110, 250, 30);

        jLabel15.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jPanel1.add(jLabel15);
        jLabel15.setBounds(230, 150, 250, 30);

        jLabel16.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jPanel1.add(jLabel16);
        jLabel16.setBounds(230, 190, 250, 30);

        jLabel17.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jPanel1.add(jLabel17);
        jLabel17.setBounds(230, 230, 250, 30);

        jLabel18.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jPanel1.add(jLabel18);
        jLabel18.setBounds(230, 270, 250, 30);

        jLabel19.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jPanel1.add(jLabel19);
        jLabel19.setBounds(230, 310, 250, 30);

        jLabel20.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jPanel1.add(jLabel20);
        jLabel20.setBounds(720, 110, 250, 30);

        jButton2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton2.setText("Proceed");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(720, 310, 250, 30);

        jLabel12.setFont(new java.awt.Font("Rockwell", 0, 22)); // NOI18N
        jLabel12.setText("Total Rent : ");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(520, 150, 200, 30);

        jLabel21.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jPanel1.add(jLabel21);
        jLabel21.setBounds(720, 150, 250, 30);

        jLabel22.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel22.setText("(Rent+Security)");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(520, 170, 150, 20);

        backbutton.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        backbutton.setText("Cancel");
        backbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(backbutton);
        backbutton.setBounds(425, 440, 120, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(30, 50, 1000, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String name = jTextField1.getText();
        String mobile = jTextField2.getText();
        String addr = jTextField3.getText();
        if(name.isEmpty() || mobile.isEmpty() || addr.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please fill all the fields first");
        }
        else{
            int cid = Integer.parseInt(jLabel14.getText());
            String sd = jLabel16.getText();
            String ed = jLabel17.getText();
            ResultSet rs = DBLoader.executeQuery("select * from booking where car_id = "+cid+" and start_date = '"+sd+"' and end_date = '"+ed+"'");
            try {
                if(rs.next()){
                    JOptionPane.showMessageDialog(this, "The Car is Already Booked For that Time");
                }
                else{
                    rs.moveToInsertRow();
                    rs.updateInt("car_id", cid);
                    rs.updateInt("price_per_day", Integer.parseInt(jLabel15.getText()));
                    rs.updateString("start_date", sd);
                    rs.updateString("end_date", ed);
                    rs.updateInt("no_of_days", Integer.parseInt(jLabel18.getText()));
                    rs.updateInt("totel_rent", Integer.parseInt(jLabel19.getText()));
                    rs.updateString("name", name);
                    rs.updateString("mobile_no", mobile);
                    rs.updateString("address", addr);
                    rs.updateString("email", UserLogin.uemail);
                    rs.updateString("payment_status", global.payment_status);
                    rs.updateString("booking_status", "success");
                    rs.insertRow();
                    JOptionPane.showMessageDialog(this, "The Car is Booked ");
                }
            } catch (SQLException ex) {
                Logger.getLogger(BookingFinal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void backbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttonActionPerformed
        new BookingSelect(this.id).setVisible(true);
        dispose();
    }//GEN-LAST:event_backbuttonActionPerformed

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        jPanel1.setBounds(10,10, jPanel1.getWidth(), jPanel1.getHeight());
    }//GEN-LAST:event_formComponentResized

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        if(evt.getKeyCode() == VK_DOWN){
            jTextField2.requestFocus();
        }
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jTextField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyPressed
        if(evt.getKeyCode() == VK_DOWN){
            jTextField3.requestFocus();
        }
        else if(evt.getKeyCode() == VK_UP){
            jTextField1.requestFocus();
        }
    }//GEN-LAST:event_jTextField2KeyPressed

    private void jTextField3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyPressed
        if(evt.getKeyCode() == VK_UP){
            jTextField2.requestFocus();
        }
    }//GEN-LAST:event_jTextField3KeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new Paygate1(jLabel21.getText(),"8888888888").setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void getvalues(int id,int price,String start,String end,int num,int rent,int sec){
        jLabel14.setText(id+"");
        jLabel15.setText(price+"");
        jLabel16.setText(start);
        jLabel17.setText(end);
        jLabel18.setText(num+"");
        jLabel19.setText(rent+"");
        jLabel20.setText(sec+"");
        jLabel21.setText(rent+sec+"");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookingFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookingFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookingFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookingFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookingFinal(0,0,"","",0,0,0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbutton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
