/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author DELL
 */
public class CarDesign extends javax.swing.JPanel {

    /**
     * Creates new form CarDesign
     */
    public CarDesign() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb1 = new javax.swing.JLabel();
        lb2 = new javax.swing.JLabel();
        lb3 = new javax.swing.JLabel();
        lb4 = new javax.swing.JLabel();
        lb5 = new javax.swing.JLabel();
        lb6 = new javax.swing.JLabel();
        lb7 = new javax.swing.JLabel();
        lb8 = new javax.swing.JLabel();
        lb9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 204, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setLayout(null);
        add(lb1);
        lb1.setBounds(20, 20, 300, 300);

        lb2.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        add(lb2);
        lb2.setBounds(350, 20, 300, 30);

        lb3.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        add(lb3);
        lb3.setBounds(350, 65, 300, 30);

        lb4.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        add(lb4);
        lb4.setBounds(350, 110, 300, 30);

        lb5.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        add(lb5);
        lb5.setBounds(350, 155, 300, 30);

        lb6.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        add(lb6);
        lb6.setBounds(350, 200, 300, 30);

        lb7.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        add(lb7);
        lb7.setBounds(350, 245, 300, 30);

        lb8.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        add(lb8);
        lb8.setBounds(350, 290, 300, 30);

        lb9.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        lb9.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(lb9);
        lb9.setBounds(650, 45, 500, 255);

        jLabel1.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabel1.setText("Description :");
        add(jLabel1);
        jLabel1.setBounds(650, 20, 220, 22);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel lb1;
    public javax.swing.JLabel lb2;
    public javax.swing.JLabel lb3;
    public javax.swing.JLabel lb4;
    public javax.swing.JLabel lb5;
    public javax.swing.JLabel lb6;
    public javax.swing.JLabel lb7;
    public javax.swing.JLabel lb8;
    public javax.swing.JLabel lb9;
    // End of variables declaration//GEN-END:variables
}
