
import java.awt.*;
import java.awt.event.*;
import java.awt.image.*;
import java.io.*;
import java.sql.*;
import java.util.logging.*;
import javax.imageio.*;
import javax.swing.*;
import db.DBLoader;

public class UserHome extends javax.swing.JFrame {
    /**
     * Creates new form UserHome
     */
    public UserHome() {
        ImageIcon im;
        try {
            im = new ImageIcon(ImageIO.read(new File("src\\myuploads\\generated-image (1).png")));
            setContentPane(new JLabel(im));
        } catch (IOException ex) {
            Logger.getLogger(Welcome.class.getName()).log(Level.SEVERE, null, ex);
        }
        repaint();
        
        initComponents();
        jPanel1.setOpaque(false);
        jScrollPane2.setOpaque(false);
        setSize(841,451);
        setExtendedState(MAXIMIZED_BOTH);
        setTitle("User Home");
        setLocationRelativeTo(null);
        getallcars();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new blurpanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        main = new javax.swing.JPanel(){@Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                Graphics2D g2d = (Graphics2D) g.create();
                g2d.setComposite(AlphaComposite.SrcOver);
                g2d.setColor(new Color(255, 255, 255, 215)); // white with transparency
                g2d.fillRect(0, 0, getWidth(), getHeight());
                g2d.dispose();
            }};
            jLabel1 = new javax.swing.JLabel();
            jButton1 = new mybuttondesign();
            jButton2 = new mybuttondesign();
            jButton3 = new mybuttondesign();

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
            addComponentListener(new java.awt.event.ComponentAdapter() {
                public void componentResized(java.awt.event.ComponentEvent evt) {
                    formComponentResized(evt);
                }
            });
            getContentPane().setLayout(null);

            jPanel1.setBackground(new java.awt.Color(255, 255, 255));
            jPanel1.setLayout(null);

            main.setBackground(new java.awt.Color(51, 255, 102));
            main.setOpaque(false);
            main.setLayout(null);
            jScrollPane2.setViewportView(main);

            jPanel1.add(jScrollPane2);
            jScrollPane2.setBounds(10, 140, 1490, 500);

            jLabel1.setFont(new java.awt.Font("Rockwell", 0, 80)); // NOI18N
            jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel1.setText("User Home");
            jPanel1.add(jLabel1);
            jLabel1.setBounds(560, 30, 430, 100);

            jButton1.setFont(new java.awt.Font("Rockwell", 0, 28)); // NOI18N
            jButton1.setText("Change Password");
            jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            jButton1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton1ActionPerformed(evt);
                }
            });
            jPanel1.add(jButton1);
            jButton1.setBounds(170, 670, 320, 80);

            jButton2.setFont(new java.awt.Font("Rockwell", 0, 28)); // NOI18N
            jButton2.setText("Booking History");
            jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            jButton2.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton2ActionPerformed(evt);
                }
            });
            jPanel1.add(jButton2);
            jButton2.setBounds(600, 670, 320, 80);

            jButton3.setFont(new java.awt.Font("Rockwell", 0, 28)); // NOI18N
            jButton3.setText("Logout");
            jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            jButton3.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton3ActionPerformed(evt);
                }
            });
            jPanel1.add(jButton3);
            jButton3.setBounds(1020, 670, 320, 80);

            getContentPane().add(jPanel1);
            jPanel1.setBounds(50, 10, 1510, 730);

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new UserLogin().setVisible(true);
        dispose();
        
        UserLogin.uemail = "";
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new UserChangePassword().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new UserBookingHistory().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        jPanel1.setBounds(10,10,(getWidth()-38),getHeight()-58);
    }//GEN-LAST:event_formComponentResized

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserHome().setVisible(true);
            }
        });
    }
    
    private void getallcars() {
        try {

            ResultSet rs = DBLoader.executeQuery("Select * from car_details");
            int i = 0;
            CarDesign arr[] = new CarDesign[100000000];  // Bad idea, we’ll fix this too later

            int x = 20, y = 20;

            while (rs.next()) {
                arr[i] = new CarDesign();

                int car_id = rs.getInt("Car_id");
                String car_names = rs.getString("Car_Name");
                String price_per_day_without_driver = rs.getInt("Price_per_Day_Without_Driver") + "";
                String price_per_day_with_driver = rs.getInt("Price_Per_Day_With_Driver") + "";
                String Security = rs.getString("Security");
                String photo = rs.getString("Photo");
                String description = rs.getString("Description");
                String brand = rs.getString("Brand");
                String car_type = rs.getString("Car_Type");
                String fuel_type = rs.getString("Fuel_Type");
                
                ImageIcon i2 = null;
                try {
                    
                System.out.println("Trying to load image from: " + photo);
                    File file = new File(photo);  // photo = "src/myploads/bmw m5.jpg"
                    BufferedImage img = ImageIO.read(file);
                    Image resized = img.getScaledInstance(arr[i].lb1.getWidth(), -1, Image.SCALE_SMOOTH);
                    i2 = new ImageIcon(resized);
                } catch (Exception e) {
                    System.out.println("In Photo Catch");
                    e.printStackTrace();
                }
                arr[i].lb1.setIcon(i2);

                arr[i].lb2.setText("Car Name : " + car_names);
                arr[i].lb3.setText("Brand : " + brand);
                arr[i].lb4.setText("Car Type : " + car_type);
                arr[i].lb5.setText("Fuel Type : " + fuel_type);
                arr[i].lb6.setText("Price Without Driver : " + price_per_day_without_driver);
                arr[i].lb7.setText("Price With Driver : " + price_per_day_with_driver);
                arr[i].lb8.setText("Security : " + Security);
                arr[i].lb9.setText("<html>"+ description+"</html>");

                arr[i].addMouseListener(new MouseAdapter() {
                    @Override
                    public void mouseClicked(MouseEvent e) {
                        new BookingSelect(car_id).setVisible(true);
                    }
                });

                arr[i].setBounds(x, y, main.getWidth()-50, 350);
                main.add(arr[i]);
                main.repaint();
                arr[i].repaint();
                y += 360;
                i++;
            }

            main.setPreferredSize(new Dimension(700, (350 * i)+70));
            main.revalidate();
        } catch (Exception ex) {
            System.out.println("In Catch");
            ex.printStackTrace();
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel main;
    // End of variables declaration//GEN-END:variables
}
